### ISSUE TITLE
Build number Pacman-U2.6-240828-1906-IND

### ISSUE THREAD

**Issue by shadowe1ite** [quintenvandamme/nothing_archive#3]
Where can I find files for build number Pacman-U2.6-240828-1906-IND (nothing phone 2a)

**Comment by quintenvandamme** [comment]
The build Pacman-U2.6-240828 (2.6 hotfix) can be used for all regions including india. And can be found [here](https://github.com/quintenvandamme/nothing_archive?tab=readme-ov-file#android-14-2).

**Comment by quintenvandamme** [comment]
I made a typo of the build number, the build can be found [here](https://github.com/quintenvandamme/nothing_archive?tab=readme-ov-file#android-14-2).

**Comment by shadowe1ite** [comment]
> I made a typo of the build number, the build can be found [here](https://github.com/quintenvandamme/nothing_archive?tab=readme-ov-file#android-14-2).

Can you tell me where can I find these builds ?
