### ISSUE TITLE
CMF Phone 1 Android 15 Beta 1 (Tetris-V3.0-241205-0050-EEA)

### ISSUE THREAD

**Issue by donmega** [quintenvandamme/nothing_archive#8]
Hi @quintenvandamme 

Love your work! I've justed updated my CMF Phone 1 to Android 15 Beta 1. Do you have any instructions on how to extract the boot.img on this phone? Thanks a lot and keep up the great job!

**Comment by quintenvandamme** [comment]
Thanks, since i only have the incremental build there is no way to extract the init boot images

**Comment by donmega** [comment]
I have managed to extract the init_boot from my device. Please use it at your own risk! It contains both the unpatched init_boot and the patched init_boot.
[Tetris-V3.0-241205-0050-EEA.zip](https://github.com/user-attachments/files/18087169/Tetris-V3.0-241205-0050-EEA.zip)

**Comment by quintenvandamme** [comment]
Thanks, ill add it to the archive and credit you.
